apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infra-api-pvc
  namespace: infra-backend
  labels:
    app: infra-api
spec:
  storageClassName: storage-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: $volumeName
